---
# Shorewall

- name: Instalace balicku
  apt:
    state: latest
    pkg: 
      - shorewall
    update_cache: yes

- name: Whitelist portu {22, 25, 80, 443, 465, 587, 993, 995}

- name: Toggle Shorewallu
  lineinfile:
    dest: /etc/default/shorewall
    regexp: "^startup = 0"
    line: "startup = 1"
    state: present

- name: Start/restart Shorewallu
  service:
    name: shorewall
    state: restarted
    enabled: yes
