---
# Handlery pro Postfixadmina

- name: Enable Apache
  service:
    name: httpd
    state: started
    enabled: true
#  when: ansible_distribution == 'CentOS'

- name: Restart Apache
  service:
    name: httpd
    state: restarted
# when: ansible_distribution == 'CentOS'