---
# Playbook pro instalaci mailovych sluzeb

- hosts: mail
  become: true
  roles:
    - general
    - mariadb
    - dovecot
    - rspamd
    - php
    - apache
    - postfix
    - postfixadmin
    - roundcube
