---
# Tasky pro acme.sh

- name: Stazeni instalacnich souboru
  git:
    repo: https://github.com/acmesh-official/acme.sh
    dest: /tmp
    clone: true
    update: true
  tags: git
  
- name: Instalace acme.sh
  shell: cd /tmp/acme.sh && ./acme.sh --install -m {{ personal_email }}
  tags: acme_sh

- name: Vystaveni certifikatu
  shell: acme.sh --issue --apache -d {{ mail_fqdn }} -d {{ smtp_fqdn }} -d {{ imap_fqdn }}
  tags: acme_sh

- name: Vytvoreni adresare pro fullchain certifikatu
  file:
    path: /etc/ssl/fullchain
    state: directory
    mode: 0700 # mozna ma byt jinak

- name: Instalace/kopirovani certifikatu
  shell:
    acme.sh --install-cert -d {{ mail_fqdn }} -d {{ smtp_fqdn }} -d {{ imap_fqdn }} \
    --cert-file {{ cert_path  }} --key-file {{ key_path }} --fullchain-file {{ fullchain_path }}
  tags: acme_sh

- name: Odstraneni tempu
  file:
    path: /tmp/acme.sh
    state: absent
  tags: acme_sh
