---
# Globalni promenne

# Mail server
host: mail
domain: sic.cz
ip_address: "{{ ansible_default_ipv4.address }}"
mail_fqdn: "{{ host }}.{{ domain }}"
smtp_fqdn: "smtp.{{ domain }}"
imap_fqdn: "imap.{{ domain }}"
mail_user: mail
email_for_updates: "{{ mail_user }}@{{ domain }}"

# Postfixadmin
path_postfixadmin: /var/www/postfixadmin
mysql_hostname: "{{ mail_fqdn }}"
mysql_database: postfix
mysql_username: postfixadmin
mysql_password: heslo # DO VAULTU
setup_password: heslo # DO VAULTU

personal_email: 

whitelist_ports:
  - "22" # SSH
  - "25" # SMTP
  - "80" # HTTP
  - "443" # HTTP/HTTPS
  - "465" # SMTP/SMTPS
  - "587" # SMTPS
  - "993" # IMAP SSL
  - "995" # POP3 SSL/TLS
