---
# Globalni promenne

# Hesla
vault_vmail_pass: "{{ vmail_pass }}"
vault_mail_user_pass: "{{ mail_user_pass }}"
vault_rspamadm_pass: "{{ rspamadm_pass }}"
rspamadm_pass_hash: # HACK1

# Mail server
host: mail
domain: sic.cz
ip_address: "{{ ansible_default_ipv4.address }}"
mail_fqdn: "{{ host }}.{{ domain }}"
## Aliasy pro mail_fqdn
smtp_fqdn: "smtp.{{ domain }}"
imap_fqdn: "imap.{{ domain }}"

mail_user: mail
email_for_updates: "{{ mail_user }}@{{ domain }}"

# Zabezpeceni
dovecot_enc: SHA512-CRYPT

## Certifikaty
cert_path: /etc/ssl/certs/cert.pem
key_path: /etc/ssl/private/key.pem
fullchain_path: /etc/ssl/fullchain/fullchain.pem

# SSH klice
ssh_key_priv: /root/.ssh/id_rsa
ssh_key_pub: /root/.ssh/id_rsa.pub

# Postfixadmin
postfixadmin_path: /var/www/postfixadmin
mysql_hostname: "{{ mail_fqdn }}"
mysql_database: postfix
mysql_username: postfixadmin
vault_mysql_pass: "{{ mysql_pass }}"
vault_setup_pass: "{{ setup_pass}}"

personal_email: 

whitelist_ports:
  - 22 # SSH
  - 25 # SMTP
  - 80 # HTTP
  - 443 # HTTP/HTTPS
  - 465 # SMTP/SMTPS
  - 587 # SMTPS
  - 993 # IMAP SSL
  - 995 # POP3 SSL/TLS
