---

# System
base_image_name: debian-11-genericcloud-amd64.qcow2
base_image_url: https://cloud.debian.org/images/cloud/bullseye/latest/{{ base_image_name }}
base_image_sha: a5d7f8c1b304cc951ccf943982217229a8225794cffd799ced25fab987a968f8
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: mail-server
vm_vcpus: 1
vm_ram_mb: 1024
vm_net: default
vm_root_pass: root
ssh_key: /root/.ssh/id_rsa.pub
path_hosts: /ansible-mail-server/hosts

# Mail server
host: mail.server
domain: sic
ip_address: "{{ ansible_default_ipv4.address }}"
mail_fqdn: "{{ host }}.{{ domain }}"
smtp_fqdn: "smtp.{{ domain }}"
imap_fqdn: "imap.{{ domain }}"
mail_user: mail
email_for_updates: "{{ mail_user }}@{{ domain }}"

# Postfixadmin
path_postfixadmin: /var/www/postfixadmin
mysql_hostname: localhost
mysql_database: postfix
mysql_username: postfixadmin
mysql_password: heslo # DO VAULTU
setup_password: heslo # DO VAULTU
