---
# Molecule test playbook

- hosts: all
  become: true
  roles:
    - general
    - acme_sh
    - mariadb
    - dovecot
    - postfix
    - rspamd
    - php
    - apache
    - postfixadmin
    - roundcube
    - shorewall
