---
# This is the top-level playbook

- hosts: all
  become: true
  roles:
    - debian
    - general
    - mariadb
    - dovecot
    - postfix
    - rspamd
    - rspamd
    - php
    - apache
    - postfixadmin
    - roundcube
