---
# Postfixadmin

- name: Template databaze
  template:
    src: template/database.sql.j2
    dest: /tmp/database.sql
  tags: mysql

- name: Vytvoreni databaze
  command: mysql --execute="source /tmp/database.sql;"
  tags: mysql

- name: Odstraneni tempu
  file:
    state: absent
    path: /tmp/database.sql
  tags: mysql

# https://stackoverflow.com/a/39951905
#shell: "mysql << EOF
#  CREATE DATABASE {{ mysql_database }};
#  CREATE USER '{{ mysql_username }}'@'{{ mail_fqdn }}' IDENTIFIED BY '{{ vault_mysql_pass }}';
#  GRANT ALL PRIVILEGES ON `{{ mysql_database }}` . * TO '{{ mysql_username }}'@'{{ mail_fqdn }}';
#  FLUSH PRIVILEGES;
#  EOF"

# https://github.com/Nainterceptor/ansible-role-postfixadmin
# ↓ ↓ ↓ ↓ ↓ ↓

- name: Stazeni taru
  get_url:
    url: https://sourceforge.net/projects/postfixadmin/files/latest/download
    dest: /tmp/postfixadmin-latest.tar.gz
  tags: postfixadmin

- name: Vytvoreni cesty
  file:
    dest: "{{ postfixadmin_path }}"
    state: directory
    recurse: true
    group: apache
    owner: apache
  tags: postfixadmin

- name: Rozbaleni taru
  command: tar -C {{ postfixadmin_path }} -xvf /tmp/postfixadmin-latest.tar.gz
# args:
#   creates: "{{ postfixadmin_path }}/index.php"
  become: true
  become_user: apache
  tags: postfixadmin

- name: Nahrazeni httpd.service
  copy: src=../files/httpd.service dest=/usr/lib/systemd/system/httpd.service
  notify:
    - Enable Apache
    - Restart Apache
  tags: postfixadmin

- name: Template httpd postfixadmin configu
  template: src=../files/httpd.conf.j2 dest=/etc/httpd/conf.d/postfixadmin.conf
  tags: postfixadmin

- name: Odstraneni httpd welcome configu
  file:
    dest: "/etc/httpd/conf.d/welcome.conf"
    state: absent
  notify:
    - Restart Apache
  tags: postfixadmin

- name: Template konfigurace Postfixadmina
  template: src=../templates/config.inc.php.j2 dest={{ postfixadmin_path }}/config.inc.php
  tags: postfixadmin
